theme: jekyll-theme-minimal
url: "https://yqjing.github.io"
plugins:
  - jekyll-seo-tag

title: Jing's Homepage
description: New Homepage using Jekyll  # the second wording in tab, can be omitted.





